# Kitty Config
# cngba, Sep 2 2026
#
# Guide: https://gist.github.com/thisisadityarao/dce2ce1b5053a458927dcba884a48cd1


# vim:fileencoding=utf-8:foldmethod=marker

# Fonts

font_family       SpaceMono Nerd Font
#bold_font        JetBrains Mono Bold
#italic_font      JetBrains Mono Italic
#bold_italic_font JetBrains Mono Bold Italic

font_size 15.0

cursor_shape underline

background_opacity 0.88

confirm_os_window_close 0

enabled_layouts *

shell fish

map F7 layout_action rotate

map shift+up move_window up
map shift+left move_window left
map shift+down move_window down
map shift+right move_window right

map ctrl+left neighboring_window left
map ctrl+right neighboring_window right
map ctrl+up neighboring_window up
map ctrl+down neighboring_window down

map shift+insert paste_from_clipboard



include Symfonic.conf
